version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Replace with a strong password
      MYSQL_DATABASE: stock_dashboard
      MYSQL_USER: user # Replace with your desired username
      MYSQL_PASSWORD: password # Replace with a strong password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: user # Match the MySQL service username
      DATABASE_PASSWORD: password # Match the MySQL service password
      DATABASE_NAME: stock_dashboard # Match the MySQL service database name
    networks:
      - app-network
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: stk-frontend
    container_name: frontend_app
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
